Lure.Application.Run();
require('./Header/Header');
// require('./Navigator/navigator');
require('./SideBar/checkingBox');
// require('./SideBar/selectBox');
// require('./Modules/Elfs');
// require('./Modules/Gnomes');
// require('./Modules/Humans');
// require('./Modules/Ogres');
// require('./Modules/Orcs');
// require('./Modules/Protos');
// require('./Modules/Trolls');
require('./Modules/DataDash');