Lure.Application.Run();
require('/Navigator/navigator');
require('./Modules/Elfs');
require('./Modules/Gnomes');
require('./Modules/Humans');
require('./Modules/Ogres');
require('./Modules/Orcs');
require('./Modules/Protos');
require('./Modules/Trolls');